name: enhanced_image_painter
description: A comprehensive Flutter package for drawing, annotating, and editing images with advanced features including customizable backgrounds, export functionality, and FlutterFlow integration.
version: 1.3.4
homepage: https://github.com/djcnnrs/Flutter-Image-Painter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0